version: "3"

services:
  server:
    build: .
    command: [ "python", "-u", "./src/main.py" ]
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      # - TZ=ETC/GMT+2
      - PYTHONUNBUFFERED=1

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6380"
