service: aws-python-flask-api-project

frameworkVersion: '2'
# useDotenv: true

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: dev
  profile: serverless-admin
  region: us-east-2
  memorySize: 1024 # Overwrite the default memory size. Default is 1024
  timeout: 6 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements

